#
# Copyright (C) 2015 Analog Devices, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_ZYNQ_PICOZED_SDR2) += usb.o ether.o run_elf.o ad9361.o loopback.o
obj-$(CONFIG_ZYNQ_PICOZED_SDR2_BRK) += usb.o ether.o buttons.o
